### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by thenewguy** [angeal185/jquery-hash#1]
It would be helpful if you posted some minimal browser support in the Readme.  

Since this is a jquery plugin, does it support all browsers jquery supports? 

Just happened across this doing some research on uploading file chunks with hash for integrity checks.  Not familiar with the crypto api.  Might help someone else along the way =)

**Comment by angeal185** [comment]
Browser support for jquery isn't an issue here, but browser support for the web crypto api could be if you wanted support for obsolete browsers. For example, the web crypto api for internet explorer is >= 11

[https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API](url)
